version: '3'

services:
  nodejs_database:
    container_name: nodejs_database
    image: mongo:4.0.22-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    volumes:
#      - ./var/post-database:/data/db

  nodejs_backend:
    container_name: nodejs_backend
    image: nodejs_backend:latest # <-- change to the image name you built
    restart: always
    environment:
      MONGO_URL: ${POST_MONGO_URL}
      MONGO_DBNAME: ${MONGO_DBNAME}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      - nodejs_database
    ports:
      - 4000:4000
    command: npm run dev # <-- run the dev server